name: 'For Yara '
favicon: null
layout_spectrum: 0.9940788934472948
typography_spectrum: 0.7440194147638977
title: Florist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.04321912699379027
  lightness: 0.6972013937775046
  saturation: 0.973896789830178
  rhythmicContrast: 0.8191310556139797
purpose: []
